 var sample_data = [
    {"year": 2009, "gender": "Female", "cbo": "Comércio", "employee_count": 4},
    {"year": 2009, "gender": "Female", "cbo": "Administração Pública", "employee_count": 7},
    {"year": 2009, "gender": "Female", "cbo": "Indústrias de Transformação", "employee_count": 2},
    {"year": 2009, "gender": "Female", "cbo": "Atividades Administrativas", "employee_count": 4},
    {"year": 2009, "gender": "Female", "cbo": "Construção", "employee_count": 7},
    {"year": 2009, "gender": "Female", "cbo": "Transporte e correio", "employee_count": 2},
    {"year": 2009, "gender": "Female", "cbo": "Saúde e Serviços Sociais", "employee_count": 4},
    {"year": 2009, "gender": "Female", "cbo": "Educação", "employee_count": 7},
    {"year": 2009, "gender": "Female", "cbo": "Alojamento e Alimentação", "employee_count": 2},
    {"year": 2009, "gender": "Female", "cbo": "Agropecuária", "employee_count": 4},
    {"year": 2009, "gender": "Female", "cbo": "Outros Serviços", "employee_count": 7},
    {"year": 2009, "gender": "Female", "cbo": "Serviços Especializados", "employee_count": 2},
    {"year": 2009, "gender": "Female", "cbo": "Atividades Financeiras", "employee_count": 4},
    {"year": 2009, "gender": "Female", "cbo": "Informação e Comunicação", "employee_count": 7},
    {"year": 2009, "gender": "Female", "cbo": "Saneamento Básico", "employee_count": 2},
    {"year": 2009, "gender": "Female", "cbo": "Indústrias Extrativas", "employee_count": 4},
    {"year": 2009, "gender": "Female", "cbo": "Artes, Cultura e Recreação", "employee_count": 7},
    {"year": 2009, "gender": "Female", "cbo": "Atividades Imobiliárias", "employee_count": 2},
    {"year": 2009, "gender": "Female", "cbo": "Eletricidade e Gás", "employee_count": 4},
    {"year": 2009, "gender": "Female", "cbo": "Serviços Domésticos", "employee_count": 7},
    {"year": 2009, "gender": "Female", "cbo": "Organismos Internacionais", "employee_count": 2},

    {"year": 2009, "gender": "Male", "cbo": "Comércio", "employee_count": 6},
    {"year": 2009, "gender": "Male", "cbo": "Administração Pública", "employee_count": 3},
    {"year": 2009, "gender": "Male", "cbo": "Indústrias de Transformação", "employee_count": 8},
    {"year": 2009, "gender": "Male", "cbo": "Atividades Administrativas", "employee_count": 6},
    {"year": 2009, "gender": "Male", "cbo": "Construção", "employee_count": 3},
    {"year": 2009, "gender": "Male", "cbo": "Transporte e correio", "employee_count": 8},
    {"year": 2009, "gender": "Male", "cbo": "Saúde e Serviços Sociais", "employee_count": 6},
    {"year": 2009, "gender": "Male", "cbo": "Educação", "employee_count": 3},
    {"year": 2009, "gender": "Male", "cbo": "Alojamento e Alimentação", "employee_count": 8},
    {"year": 2009, "gender": "Male", "cbo": "Agropecuária", "employee_count": 6},
    {"year": 2009, "gender": "Male", "cbo": "Outros Serviços", "employee_count": 3},
    {"year": 2009, "gender": "Male", "cbo": "Serviços Especializados", "employee_count": 8},
    {"year": 2009, "gender": "Male", "cbo": "Atividades Financeiras", "employee_count": 6},
    {"year": 2009, "gender": "Male", "cbo": "Informação e Comunicação", "employee_count": 3},
    {"year": 2009, "gender": "Male", "cbo": "Saneamento Básico", "employee_count": 8},
    {"year": 2009, "gender": "Male", "cbo": "Indústrias Extrativas", "employee_count": 6},
    {"year": 2009, "gender": "Male", "cbo": "Artes, Cultura e Recreação", "employee_count": 3},
    {"year": 2009, "gender": "Male", "cbo": "Atividades Imobiliárias", "employee_count": 8},
    {"year": 2009, "gender": "Male", "cbo": "Eletricidade e Gás", "employee_count": 6},
    {"year": 2009, "gender": "Male", "cbo": "Serviços Domésticos", "employee_count": 3},
    {"year": 2009, "gender": "Male", "cbo": "Organismos Internacionais", "employee_count": 8},

    {"year": 2010, "gender": "Female", "cbo": "Comércio", "employee_count": 5},
    {"year": 2010, "gender": "Female", "cbo": "Administração Pública", "employee_count": 8},
    {"year": 2010, "gender": "Female", "cbo": "Indústrias de Transformação", "employee_count": 3},
    {"year": 2010, "gender": "Female", "cbo": "Atividades Administrativas", "employee_count": 5},
    {"year": 2010, "gender": "Female", "cbo": "Construção", "employee_count": 8},
    {"year": 2010, "gender": "Female", "cbo": "Transporte e correio", "employee_count": 3},
    {"year": 2010, "gender": "Female", "cbo": "Saúde e Serviços Sociais", "employee_count": 5},
    {"year": 2010, "gender": "Female", "cbo": "Educação", "employee_count": 8},
    {"year": 2010, "gender": "Female", "cbo": "Alojamento e Alimentação", "employee_count": 3},
    {"year": 2010, "gender": "Female", "cbo": "Agropecuária", "employee_count": 5},
    {"year": 2010, "gender": "Female", "cbo": "Outros Serviços", "employee_count": 8},
    {"year": 2010, "gender": "Female", "cbo": "Serviços Especializados", "employee_count": 3},
    {"year": 2010, "gender": "Female", "cbo": "Atividades Financeiras", "employee_count": 5},
    {"year": 2010, "gender": "Female", "cbo": "Informação e Comunicação", "employee_count": 8},
    {"year": 2010, "gender": "Female", "cbo": "Saneamento Básico", "employee_count": 3},
    {"year": 2010, "gender": "Female", "cbo": "Indústrias Extrativas", "employee_count": 5},
    {"year": 2010, "gender": "Female", "cbo": "Artes, Cultura e Recreação", "employee_count": 8},
    {"year": 2010, "gender": "Female", "cbo": "Atividades Imobiliárias", "employee_count": 3},
    {"year": 2010, "gender": "Female", "cbo": "Eletricidade e Gás", "employee_count": 5},
    {"year": 2010, "gender": "Female", "cbo": "Serviços Domésticos", "employee_count": 8},
    {"year": 2010, "gender": "Female", "cbo": "Organismos Internacionais", "employee_count": 3},

    {"year": 2010, "gender": "Male", "cbo": "Comércio", "employee_count": 7},
    {"year": 2010, "gender": "Male", "cbo": "Administração Pública", "employee_count": 4},
    {"year": 2010, "gender": "Male", "cbo": "Indústrias de Transformação", "employee_count": 9},
    {"year": 2010, "gender": "Male", "cbo": "Atividades Administrativas", "employee_count": 7},
    {"year": 2010, "gender": "Male", "cbo": "Construção", "employee_count": 4},
    {"year": 2010, "gender": "Male", "cbo": "Transporte e correio", "employee_count": 9},
    {"year": 2010, "gender": "Male", "cbo": "Saúde e Serviços Sociais", "employee_count": 7},
    {"year": 2010, "gender": "Male", "cbo": "Educação", "employee_count": 4},
    {"year": 2010, "gender": "Male", "cbo": "Alojamento e Alimentação", "employee_count": 9},
    {"year": 2010, "gender": "Male", "cbo": "Agropecuária", "employee_count": 7},
    {"year": 2010, "gender": "Male", "cbo": "Outros Serviços", "employee_count": 4},
    {"year": 2010, "gender": "Male", "cbo": "Serviços Especializados", "employee_count": 9},
    {"year": 2010, "gender": "Male", "cbo": "Atividades Financeiras", "employee_count": 7},
    {"year": 2010, "gender": "Male", "cbo": "Informação e Comunicação", "employee_count": 4},
    {"year": 2010, "gender": "Male", "cbo": "Saneamento Básico", "employee_count": 9},
    {"year": 2010, "gender": "Male", "cbo": "Indústrias Extrativas", "employee_count": 7},
    {"year": 2010, "gender": "Male", "cbo": "Artes, Cultura e Recreação", "employee_count": 4},
    {"year": 2010, "gender": "Male", "cbo": "Atividades Imobiliárias", "employee_count": 9},
    {"year": 2010, "gender": "Male", "cbo": "Eletricidade e Gás", "employee_count": 7},
    {"year": 2010, "gender": "Male", "cbo": "Serviços Domésticos", "employee_count": 4},
    {"year": 2010, "gender": "Male", "cbo": "Organismos Internacionais", "employee_count": 9},

    {"year": 2011, "gender": "Female", "cbo": "Comércio", "employee_count": 6},
    {"year": 2011, "gender": "Female", "cbo": "Administração Pública", "employee_count": 9},
    {"year": 2011, "gender": "Female", "cbo": "Indústrias de Transformação", "employee_count": 4},
    {"year": 2011, "gender": "Female", "cbo": "Atividades Administrativas", "employee_count": 6},
    {"year": 2011, "gender": "Female", "cbo": "Construção", "employee_count": 9},
    {"year": 2011, "gender": "Female", "cbo": "Transporte e correio", "employee_count": 4},
    {"year": 2011, "gender": "Female", "cbo": "Saúde e Serviços Sociais", "employee_count": 6},
    {"year": 2011, "gender": "Female", "cbo": "Educação", "employee_count": 9},
    {"year": 2011, "gender": "Female", "cbo": "Alojamento e Alimentação", "employee_count": 4},
    {"year": 2011, "gender": "Female", "cbo": "Agropecuária", "employee_count": 6},
    {"year": 2011, "gender": "Female", "cbo": "Outros Serviços", "employee_count": 9},
    {"year": 2011, "gender": "Female", "cbo": "Serviços Especializados", "employee_count": 4},
    {"year": 2011, "gender": "Female", "cbo": "Atividades Financeiras", "employee_count": 6},
    {"year": 2011, "gender": "Female", "cbo": "Informação e Comunicação", "employee_count": 9},
    {"year": 2011, "gender": "Female", "cbo": "Saneamento Básico", "employee_count": 4},
    {"year": 2011, "gender": "Female", "cbo": "Indústrias Extrativas", "employee_count": 6},
    {"year": 2011, "gender": "Female", "cbo": "Artes, Cultura e Recreação", "employee_count": 9},
    {"year": 2011, "gender": "Female", "cbo": "Atividades Imobiliárias", "employee_count": 4},
    {"year": 2011, "gender": "Female", "cbo": "Eletricidade e Gás", "employee_count": 6},
    {"year": 2011, "gender": "Female", "cbo": "Serviços Domésticos", "employee_count": 9},
    {"year": 2011, "gender": "Female", "cbo": "Organismos Internacionais", "employee_count": 4},

    {"year": 2011, "gender": "Male", "cbo": "Comércio", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Administração Pública", "employee_count": 5},
    {"year": 2011, "gender": "Male", "cbo": "Indústrias de Transformação", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Atividades Administrativas", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Construção", "employee_count": 5},
    {"year": 2011, "gender": "Male", "cbo": "Transporte e correio", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Saúde e Serviços Sociais", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Educação", "employee_count": 5},
    {"year": 2011, "gender": "Male", "cbo": "Alojamento e Alimentação", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Agropecuária", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Outros Serviços", "employee_count": 5},
    {"year": 2011, "gender": "Male", "cbo": "Serviços Especializados", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Atividades Financeiras", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Informação e Comunicação", "employee_count": 5},
    {"year": 2011, "gender": "Male", "cbo": "Saneamento Básico", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Indústrias Extrativas", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Artes, Cultura e Recreação", "employee_count": 5},
    {"year": 2011, "gender": "Male", "cbo": "Atividades Imobiliárias", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Eletricidade e Gás", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Serviços Domésticos", "employee_count": 5},
    {"year": 2011, "gender": "Male", "cbo": "Organismos Internacionais", "employee_count": 8},
  ];

  var sample_data_comercio = [
        {"year": 2010, "gender": "Female", "cbo": "Comercio varejista", "employee_count":27},
        {"year": 2010,"gender": "Female", "cbo": "Comercio atacadista", "employee_count":19},
        {"year": 2010,"gender": "Female", "cbo": "Comercio de Automotores", "employee_count":5},
        {"year": 2011, "gender": "Female", "cbo": "Comercio varejista", "employee_count":30},
        {"year": 2011,"gender": "Female", "cbo": "Comercio atacadista", "employee_count":21},
        {"year": 2011,"gender": "Female", "cbo": "Comercio de Automotores", "employee_count":8},

        {"year": 2010,"gender": "Male", "cbo": "Comercio varejista", "employee_count":16},
        {"year": 2010,"gender": "Male", "cbo": "Comercio atacadista", "employee_count":25},
        {"year": 2010,"gender": "Male", "cbo": "Comercio de Automotores", "employee_count":33},
        {"year": 2011,"gender": "Male", "cbo": "Comercio varejista", "employee_count":8},
        {"year": 2011,"gender": "Male", "cbo": "Comercio atacadista", "employee_count":21},
        {"year": 2011,"gender": "Male", "cbo": "Comercio de Automotores", "employee_count":30}
    ];

      var sample_data_industrias_de_transformacao = [
        {"year": 2010, "gender": "Female", "cbo": "Produtos Alimentícios", "employee_count":27},
        {"year": 2010,"gender": "Female", "cbo": "Confecção e Vestuário", "employee_count":19},
        {"year": 2010,"gender": "Female", "cbo": "Produtos de Metal", "employee_count":5},
        {"year": 2011, "gender": "Female", "cbo": "Veículos Automotores", "employee_count":30},
        {"year": 2011,"gender": "Female", "cbo": "Produtos de Minerais Não-Metálicos", "employee_count":21},
        {"year": 2011,"gender": "Female", "cbo": "Produtos de Borracha e de Material Plástico", "employee_count":8},
        {"year": 2010, "gender": "Female", "cbo": "Máquinas e Equipamentos", "employee_count":20},
        {"year": 2010,"gender": "Female", "cbo": "Couro e Calçados", "employee_count":15},
        {"year": 2010,"gender": "Female", "cbo": "Produtos Têxteis", "employee_count":2},
        {"year": 2011, "gender": "Female", "cbo": "Móveis", "employee_count":23},
        {"year": 2011,"gender": "Female", "cbo": "Produtos Químicos", "employee_count":22},
        {"year": 2011,"gender": "Female", "cbo": "Metalurgia", "employee_count":3},
        {"year": 2010, "gender": "Female", "cbo": "Produtos e Materiais Elétricos", "employee_count":15},
        {"year": 2010,"gender": "Female", "cbo": "Produtos de Madeira", "employee_count":12},
        {"year": 2010,"gender": "Female", "cbo": "Manutenção de Máquinas e Equipamentos", "employee_count":8},
        {"year": 2011, "gender": "Female", "cbo": "Papel e Celulose", "employee_count":38},
        {"year": 2011,"gender": "Female", "cbo": "Papel e Celulose", "employee_count":41},
        {"year": 2011,"gender": "Female", "cbo": "Coque e Derivados de Petróleo", "employee_count":8},
        {"year": 2011,"gender": "Female", "cbo": "Produtos Diversos", "employee_count":12},
        {"year": 2010, "gender": "Female", "cbo": "Bebidas", "employee_count":27},
        {"year": 2010,"gender": "Female", "cbo": "Impressão e Reprodução de Gravações", "employee_count":22},
        {"year": 2010,"gender": "Female", "cbo": "Outros Equipamentos de Transporte", "employee_count":9},
        {"year": 2011, "gender": "Female", "cbo": "Produtos Farmoquímicos e Farmacêuticos", "employee_count":21},
        {"year": 2011,"gender": "Female", "cbo": "Produtos do Fumo", "employee_count":21},
        {"year": 2011, "gender": "Female", "cbo": "Produtos Alimentícios", "employee_count":15},
        {"year": 2011,"gender": "Female", "cbo": "Confecção e Vestuário", "employee_count":19},
        {"year": 2011,"gender": "Female", "cbo": "Produtos de Metal", "employee_count":5},
        {"year": 2010, "gender": "Female", "cbo": "Veículos Automotores", "employee_count":30},
        {"year": 2010,"gender": "Female", "cbo": "Produtos de Minerais Não-Metálicos", "employee_count":21},
        {"year": 2010,"gender": "Female", "cbo": "Produtos de Borracha e de Material Plástico", "employee_count":8},
        {"year": 2011, "gender": "Female", "cbo": "Máquinas e Equipamentos", "employee_count":20},
        {"year": 2011,"gender": "Female", "cbo": "Couro e Calçados", "employee_count":15},
        {"year": 2011,"gender": "Female", "cbo": "Produtos Têxteis", "employee_count":2},
        {"year": 2010, "gender": "Female", "cbo": "Móveis", "employee_count":23},
        {"year": 2010,"gender": "Female", "cbo": "Produtos Químicos", "employee_count":22},
        {"year": 2010,"gender": "Female", "cbo": "Metalurgia", "employee_count":3},
        {"year": 2011, "gender": "Female", "cbo": "Produtos e Materiais Elétricos", "employee_count":15},
        {"year": 2011,"gender": "Female", "cbo": "Produtos de Madeira", "employee_count":12},
        {"year": 2011,"gender": "Female", "cbo": "Manutenção de Máquinas e Equipamentos", "employee_count":8},
        {"year": 2010, "gender": "Female", "cbo": "Papel e Celulose", "employee_count":38},
        {"year": 2010,"gender": "Female", "cbo": "Papel e Celulose", "employee_count":41},
        {"year": 2010,"gender": "Female", "cbo": "Coque e Derivados de Petróleo", "employee_count":8},
        {"year": 2011,"gender": "Female", "cbo": "Produtos Diversos", "employee_count":12},
        {"year": 2011, "gender": "Female", "cbo": "Bebidas", "employee_count":1},
        {"year": 2011,"gender": "Female", "cbo": "Impressão e Reprodução de Gravações", "employee_count":22},
        {"year": 2010,"gender": "Female", "cbo": "Outros Equipamentos de Transporte", "employee_count":9},
        {"year": 2010, "gender": "Female", "cbo": "Produtos Farmoquímicos e Farmacêuticos", "employee_count":21},
        {"year": 2010,"gender": "Female", "cbo": "Produtos do Fumo", "employee_count":21},


        {"year": 2010, "gender": "Male", "cbo": "Produtos Alimentícios", "employee_count":29},
        {"year": 2010,"gender": "Male", "cbo": "Confecção e Vestuário", "employee_count":18},
        {"year": 2010,"gender": "Male", "cbo": "Produtos de Metal", "employee_count":5},
        {"year": 2011, "gender": "Male", "cbo": "Veículos Automotores", "employee_count":30},
        {"year": 2011,"gender": "Male", "cbo": "Produtos de Minerais Não-Metálicos", "employee_count":21},
        {"year": 2011,"gender": "Male", "cbo": "Produtos de Borracha e de Material Plástico", "employee_count":8},
        {"year": 2010, "gender": "Male", "cbo": "Máquinas e Equipamentos", "employee_count":31},
        {"year": 2010,"gender": "Male", "cbo": "Couro e Calçados", "employee_count":19},
        {"year": 2010,"gender": "Male", "cbo": "Produtos Têxteis", "employee_count":6},
        {"year": 2011, "gender": "Male", "cbo": "Móveis", "employee_count":32},
        {"year": 2011,"gender": "Male", "cbo": "Produtos Químicos", "employee_count":21},
        {"year": 2011,"gender": "Male", "cbo": "Metalurgia", "employee_count":8},
        {"year": 2010, "gender": "Male", "cbo": "Produtos e Materiais Elétricos", "employee_count":41},
        {"year": 2010,"gender": "Male", "cbo": "Produtos de Madeira", "employee_count":20},
        {"year": 2010,"gender": "Male", "cbo": "Manutenção de Máquinas e Equipamentos", "employee_count":2},
        {"year": 2011, "gender": "Male", "cbo": "Papel e Celulose", "employee_count":33},
        {"year": 2011,"gender": "Male", "cbo": "Papel e Celulose", "employee_count":21},
        {"year": 2011,"gender": "Male", "cbo": "Coque e Derivados de Petróleo", "employee_count":8},
        {"year": 2011,"gender": "Male", "cbo": "Produtos Diversos", "employee_count":8},
        {"year": 2010, "gender": "Male", "cbo": "Bebidas", "employee_count":12},
        {"year": 2010,"gender": "Male", "cbo": "Impressão e Reprodução de Gravações", "employee_count":21},
        {"year": 2010,"gender": "Male", "cbo": "Outros Equipamentos de Transporte", "employee_count":1},
        {"year": 2011, "gender": "Male", "cbo": "Produtos Farmoquímicos e Farmacêuticos", "employee_count":27},
        {"year": 2011,"gender": "Male", "cbo": "Produtos do Fumo", "employee_count":21},

        {"year": 2011, "gender": "Male", "cbo": "Produtos Alimentícios", "employee_count":29},
        {"year": 2011,"gender": "Male", "cbo": "Confecção e Vestuário", "employee_count":18},
        {"year": 2011,"gender": "Male", "cbo": "Produtos de Metal", "employee_count":5},
        {"year": 2010, "gender": "Male", "cbo": "Veículos Automotores", "employee_count":30},
        {"year": 2010,"gender": "Male", "cbo": "Produtos de Minerais Não-Metálicos", "employee_count":21},
        {"year": 2010,"gender": "Male", "cbo": "Produtos de Borracha e de Material Plástico", "employee_count":8},
        {"year": 2011, "gender": "Male", "cbo": "Máquinas e Equipamentos", "employee_count":31},
        {"year": 2011,"gender": "Male", "cbo": "Couro e Calçados", "employee_count":19},
        {"year": 2011,"gender": "Male", "cbo": "Produtos Têxteis", "employee_count":6},
        {"year": 2010, "gender": "Male", "cbo": "Móveis", "employee_count":32},
        {"year": 2010,"gender": "Male", "cbo": "Produtos Químicos", "employee_count":21},
        {"year": 2010,"gender": "Male", "cbo": "Metalurgia", "employee_count":8},
        {"year": 2011, "gender": "Male", "cbo": "Produtos e Materiais Elétricos", "employee_count":41},
        {"year": 2011,"gender": "Male", "cbo": "Produtos de Madeira", "employee_count":20},
        {"year": 2011,"gender": "Male", "cbo": "Manutenção de Máquinas e Equipamentos", "employee_count":2},
        {"year": 2010, "gender": "Male", "cbo": "Papel e Celulose", "employee_count":33},
        {"year": 2010,"gender": "Male", "cbo": "Papel e Celulose", "employee_count":21},
        {"year": 2010,"gender": "Male", "cbo": "Coque e Derivados de Petróleo", "employee_count":8},
        {"year": 2011,"gender": "Male", "cbo": "Produtos Diversos", "employee_count":8},
        {"year": 2011, "gender": "Male", "cbo": "Bebidas", "employee_count":12},
        {"year": 2011,"gender": "Male", "cbo": "Impressão e Reprodução de Gravações", "employee_count":21},
        {"year": 2010,"gender": "Male", "cbo": "Outros Equipamentos de Transporte", "employee_count":1},
        {"year": 2010, "gender": "Male", "cbo": "Produtos Farmoquímicos e Farmacêuticos", "employee_count":27},
        {"year": 2010,"gender": "Male", "cbo": "Produtos do Fumo", "employee_count":21},
    ];
        var sample_data_atividades_administrativas = [
        {"year": 2010, "gender": "Female", "cbo": "Serviços para Edifícios", "employee_count":12},
        {"year": 2010,"gender": "Female", "cbo": "Serviços de Escritório", "employee_count":15},
        {"year": 2010,"gender": "Female", "cbo": "Vigilância e Segurança", "employee_count":31},
        {"year": 2011, "gender": "Female", "cbo": "Seleção e Agenciamento de Mão-de-Obra", "employee_count":10},
        {"year": 2011,"gender": "Female", "cbo": "Aluguéis Não-Imobiliários", "employee_count":5},
        {"year": 2011,"gender": "Female", "cbo": "Agências de Viagens", "employee_count":20},

        {"year": 2010, "gender": "Male", "cbo": "Serviços para Edifícios", "employee_count":29},
        {"year": 2010,"gender": "Male", "cbo": "Serviços de Escritório", "employee_count":18},
        {"year": 2010,"gender": "Male", "cbo": "Vigilância e Segurança", "employee_count":5},
        {"year": 2011, "gender": "Male", "cbo": "Seleção e Agenciamento de Mão-de-Obra", "employee_count":30},
        {"year": 2011,"gender": "Male", "cbo": "Aluguéis Não-Imobiliários", "employee_count":21},
        {"year": 2011,"gender": "Male", "cbo": "Agências de Viagens", "employee_count":8}
        ]