 var sample_data = [
    {"year": 2009, "gender": "Female", "cbo": "Comércio", "employee_count": 4},
    {"year": 2009, "gender": "Female", "cbo": "Administração Pública", "employee_count": 7},
    {"year": 2009, "gender": "Female", "cbo": "Indústrias de Transformação", "employee_count": 2},
    {"year": 2009, "gender": "Female", "cbo": "Atividades Administrativas", "employee_count": 4},
    {"year": 2009, "gender": "Female", "cbo": "Construção", "employee_count": 7},
    {"year": 2009, "gender": "Female", "cbo": "Transporte e correio", "employee_count": 2},
    {"year": 2009, "gender": "Female", "cbo": "Saúde e Serviços Sociais", "employee_count": 4},
    {"year": 2009, "gender": "Female", "cbo": "Educação", "employee_count": 7},
    {"year": 2009, "gender": "Female", "cbo": "Alojamento e Alimentação", "employee_count": 2},
    {"year": 2009, "gender": "Female", "cbo": "Agropecuária", "employee_count": 4},
    {"year": 2009, "gender": "Female", "cbo": "Outros Serviços", "employee_count": 7},
    {"year": 2009, "gender": "Female", "cbo": "Serviços Especializados", "employee_count": 2},
    {"year": 2009, "gender": "Female", "cbo": "Atividades Financeiras", "employee_count": 4},
    {"year": 2009, "gender": "Female", "cbo": "Informação e Comunicação", "employee_count": 7},
    {"year": 2009, "gender": "Female", "cbo": "Saneamento Básico", "employee_count": 2},
    {"year": 2009, "gender": "Female", "cbo": "Indústrias Extrativas", "employee_count": 4},
    {"year": 2009, "gender": "Female", "cbo": "Artes, Cultura e Recreação", "employee_count": 7},
    {"year": 2009, "gender": "Female", "cbo": "Atividades Imobiliárias", "employee_count": 2},
    {"year": 2009, "gender": "Female", "cbo": "Eletricidade e Gás", "employee_count": 4},
    {"year": 2009, "gender": "Female", "cbo": "Serviços Domésticos", "employee_count": 7},
    {"year": 2009, "gender": "Female", "cbo": "Organismos Internacionais", "employee_count": 2},

    {"year": 2009, "gender": "Male", "cbo": "Comércio", "employee_count": 6},
    {"year": 2009, "gender": "Male", "cbo": "Administração Pública", "employee_count": 3},
    {"year": 2009, "gender": "Male", "cbo": "Indústrias de Transformação", "employee_count": 8},
    {"year": 2009, "gender": "Male", "cbo": "Atividades Administrativas", "employee_count": 6},
    {"year": 2009, "gender": "Male", "cbo": "Construção", "employee_count": 3},
    {"year": 2009, "gender": "Male", "cbo": "Transporte e correio", "employee_count": 8},
    {"year": 2009, "gender": "Male", "cbo": "Saúde e Serviços Sociais", "employee_count": 6},
    {"year": 2009, "gender": "Male", "cbo": "Educação", "employee_count": 3},
    {"year": 2009, "gender": "Male", "cbo": "Alojamento e Alimentação", "employee_count": 8},
    {"year": 2009, "gender": "Male", "cbo": "Agropecuária", "employee_count": 6},
    {"year": 2009, "gender": "Male", "cbo": "Outros Serviços", "employee_count": 3},
    {"year": 2009, "gender": "Male", "cbo": "Serviços Especializados", "employee_count": 8},
    {"year": 2009, "gender": "Male", "cbo": "Atividades Financeiras", "employee_count": 6},
    {"year": 2009, "gender": "Male", "cbo": "Informação e Comunicação", "employee_count": 3},
    {"year": 2009, "gender": "Male", "cbo": "Saneamento Básico", "employee_count": 8},
    {"year": 2009, "gender": "Male", "cbo": "Indústrias Extrativas", "employee_count": 6},
    {"year": 2009, "gender": "Male", "cbo": "Artes, Cultura e Recreação", "employee_count": 3},
    {"year": 2009, "gender": "Male", "cbo": "Atividades Imobiliárias", "employee_count": 8},
    {"year": 2009, "gender": "Male", "cbo": "Eletricidade e Gás", "employee_count": 6},
    {"year": 2009, "gender": "Male", "cbo": "Serviços Domésticos", "employee_count": 3},
    {"year": 2009, "gender": "Male", "cbo": "Organismos Internacionais", "employee_count": 8},

    {"year": 2010, "gender": "Female", "cbo": "Comércio", "employee_count": 5},
    {"year": 2010, "gender": "Female", "cbo": "Administração Pública", "employee_count": 8},
    {"year": 2010, "gender": "Female", "cbo": "Indústrias de Transformação", "employee_count": 3},
    {"year": 2010, "gender": "Female", "cbo": "Atividades Administrativas", "employee_count": 5},
    {"year": 2010, "gender": "Female", "cbo": "Construção", "employee_count": 8},
    {"year": 2010, "gender": "Female", "cbo": "Transporte e correio", "employee_count": 3},
    {"year": 2010, "gender": "Female", "cbo": "Saúde e Serviços Sociais", "employee_count": 5},
    {"year": 2010, "gender": "Female", "cbo": "Educação", "employee_count": 8},
    {"year": 2010, "gender": "Female", "cbo": "Alojamento e Alimentação", "employee_count": 3},
    {"year": 2010, "gender": "Female", "cbo": "Agropecuária", "employee_count": 5},
    {"year": 2010, "gender": "Female", "cbo": "Outros Serviços", "employee_count": 8},
    {"year": 2010, "gender": "Female", "cbo": "Serviços Especializados", "employee_count": 3},
    {"year": 2010, "gender": "Female", "cbo": "Atividades Financeiras", "employee_count": 5},
    {"year": 2010, "gender": "Female", "cbo": "Informação e Comunicação", "employee_count": 8},
    {"year": 2010, "gender": "Female", "cbo": "Saneamento Básico", "employee_count": 3},
    {"year": 2010, "gender": "Female", "cbo": "Indústrias Extrativas", "employee_count": 5},
    {"year": 2010, "gender": "Female", "cbo": "Artes, Cultura e Recreação", "employee_count": 8},
    {"year": 2010, "gender": "Female", "cbo": "Atividades Imobiliárias", "employee_count": 3},
    {"year": 2010, "gender": "Female", "cbo": "Eletricidade e Gás", "employee_count": 5},
    {"year": 2010, "gender": "Female", "cbo": "Serviços Domésticos", "employee_count": 8},
    {"year": 2010, "gender": "Female", "cbo": "Organismos Internacionais", "employee_count": 3},

    {"year": 2010, "gender": "Male", "cbo": "Comércio", "employee_count": 7},
    {"year": 2010, "gender": "Male", "cbo": "Administração Pública", "employee_count": 4},
    {"year": 2010, "gender": "Male", "cbo": "Indústrias de Transformação", "employee_count": 9},
    {"year": 2010, "gender": "Male", "cbo": "Atividades Administrativas", "employee_count": 7},
    {"year": 2010, "gender": "Male", "cbo": "Construção", "employee_count": 4},
    {"year": 2010, "gender": "Male", "cbo": "Transporte e correio", "employee_count": 9},
    {"year": 2010, "gender": "Male", "cbo": "Saúde e Serviços Sociais", "employee_count": 7},
    {"year": 2010, "gender": "Male", "cbo": "Educação", "employee_count": 4},
    {"year": 2010, "gender": "Male", "cbo": "Alojamento e Alimentação", "employee_count": 9},
    {"year": 2010, "gender": "Male", "cbo": "Agropecuária", "employee_count": 7},
    {"year": 2010, "gender": "Male", "cbo": "Outros Serviços", "employee_count": 4},
    {"year": 2010, "gender": "Male", "cbo": "Serviços Especializados", "employee_count": 9},
    {"year": 2010, "gender": "Male", "cbo": "Atividades Financeiras", "employee_count": 7},
    {"year": 2010, "gender": "Male", "cbo": "Informação e Comunicação", "employee_count": 4},
    {"year": 2010, "gender": "Male", "cbo": "Saneamento Básico", "employee_count": 9},
    {"year": 2010, "gender": "Male", "cbo": "Indústrias Extrativas", "employee_count": 7},
    {"year": 2010, "gender": "Male", "cbo": "Artes, Cultura e Recreação", "employee_count": 4},
    {"year": 2010, "gender": "Male", "cbo": "Atividades Imobiliárias", "employee_count": 9},
    {"year": 2010, "gender": "Male", "cbo": "Eletricidade e Gás", "employee_count": 7},
    {"year": 2010, "gender": "Male", "cbo": "Serviços Domésticos", "employee_count": 4},
    {"year": 2010, "gender": "Male", "cbo": "Organismos Internacionais", "employee_count": 9},

    {"year": 2011, "gender": "Female", "cbo": "Comércio", "employee_count": 6},
    {"year": 2011, "gender": "Female", "cbo": "Administração Pública", "employee_count": 9},
    {"year": 2011, "gender": "Female", "cbo": "Indústrias de Transformação", "employee_count": 4},
    {"year": 2011, "gender": "Female", "cbo": "Atividades Administrativas", "employee_count": 6},
    {"year": 2011, "gender": "Female", "cbo": "Construção", "employee_count": 9},
    {"year": 2011, "gender": "Female", "cbo": "Transporte e correio", "employee_count": 4},
    {"year": 2011, "gender": "Female", "cbo": "Saúde e Serviços Sociais", "employee_count": 6},
    {"year": 2011, "gender": "Female", "cbo": "Educação", "employee_count": 9},
    {"year": 2011, "gender": "Female", "cbo": "Alojamento e Alimentação", "employee_count": 4},
    {"year": 2011, "gender": "Female", "cbo": "Agropecuária", "employee_count": 6},
    {"year": 2011, "gender": "Female", "cbo": "Outros Serviços", "employee_count": 9},
    {"year": 2011, "gender": "Female", "cbo": "Serviços Especializados", "employee_count": 4},
    {"year": 2011, "gender": "Female", "cbo": "Atividades Financeiras", "employee_count": 6},
    {"year": 2011, "gender": "Female", "cbo": "Informação e Comunicação", "employee_count": 9},
    {"year": 2011, "gender": "Female", "cbo": "Saneamento Básico", "employee_count": 4},
    {"year": 2011, "gender": "Female", "cbo": "Indústrias Extrativas", "employee_count": 6},
    {"year": 2011, "gender": "Female", "cbo": "Artes, Cultura e Recreação", "employee_count": 9},
    {"year": 2011, "gender": "Female", "cbo": "Atividades Imobiliárias", "employee_count": 4},
    {"year": 2011, "gender": "Female", "cbo": "Eletricidade e Gás", "employee_count": 6},
    {"year": 2011, "gender": "Female", "cbo": "Serviços Domésticos", "employee_count": 9},
    {"year": 2011, "gender": "Female", "cbo": "Organismos Internacionais", "employee_count": 4},

    {"year": 2011, "gender": "Male", "cbo": "Comércio", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Administração Pública", "employee_count": 5},
    {"year": 2011, "gender": "Male", "cbo": "Indústrias de Transformação", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Atividades Administrativas", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Construção", "employee_count": 5},
    {"year": 2011, "gender": "Male", "cbo": "Transporte e correio", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Saúde e Serviços Sociais", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Educação", "employee_count": 5},
    {"year": 2011, "gender": "Male", "cbo": "Alojamento e Alimentação", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Agropecuária", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Outros Serviços", "employee_count": 5},
    {"year": 2011, "gender": "Male", "cbo": "Serviços Especializados", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Atividades Financeiras", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Informação e Comunicação", "employee_count": 5},
    {"year": 2011, "gender": "Male", "cbo": "Saneamento Básico", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Indústrias Extrativas", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Artes, Cultura e Recreação", "employee_count": 5},
    {"year": 2011, "gender": "Male", "cbo": "Atividades Imobiliárias", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Eletricidade e Gás", "employee_count": 8},
    {"year": 2011, "gender": "Male", "cbo": "Serviços Domésticos", "employee_count": 5},
    {"year": 2011, "gender": "Male", "cbo": "Organismos Internacionais", "employee_count": 8},
  ];

  var sample_data_comercio = [
        {"year": 2010, "gender": "Female", "cbo": "Comercio varejista", "employee_count":27},
        {"year": 2010,"gender": "Female", "cbo": "Comercio atacadista", "employee_count":19},
        {"year": 2010,"gender": "Female", "cbo": "Comercio de Automotores", "employee_count":5},
        {"year": 2011, "gender": "Female", "cbo": "Comercio varejista", "employee_count":30},
        {"year": 2011,"gender": "Female", "cbo": "Comercio atacadista", "employee_count":21},
        {"year": 2011,"gender": "Female", "cbo": "Comercio de Automotores", "employee_count":8},

        {"year": 2010,"gender": "Male", "cbo": "Comercio varejista", "employee_count":16},
        {"year": 2010,"gender": "Male", "cbo": "Comercio atacadista", "employee_count":25},
        {"year": 2010,"gender": "Male", "cbo": "Comercio de Automotores", "employee_count":33},
        {"year": 2011,"gender": "Male", "cbo": "Comercio varejista", "employee_count":8},
        {"year": 2011,"gender": "Male", "cbo": "Comercio atacadista", "employee_count":21},
        {"year": 2011,"gender": "Male", "cbo": "Comercio de Automotores", "employee_count":30}
    ];

      var sample_data_administracao_publica = [
        {"year": 2010, "gender": "Female", "cbo": "Comercio varejista", "employee_count":27},
        {"year": 2010,"gender": "Female", "cbo": "Comercio atacadista", "employee_count":19},
        {"year": 2010,"gender": "Female", "cbo": "Comercio de Automotores", "employee_count":5},
        {"year": 2011, "gender": "Female", "cbo": "Comercio varejista", "employee_count":30},
        {"year": 2011,"gender": "Female", "cbo": "Comercio atacadista", "employee_count":21},
        {"year": 2011,"gender": "Female", "cbo": "Comercio de Automotores", "employee_count":8},

        {"year": 2010,"gender": "Male", "cbo": "Comercio varejista", "employee_count":16},
        {"year": 2010,"gender": "Male", "cbo": "Comercio atacadista", "employee_count":25},
        {"year": 2010,"gender": "Male", "cbo": "Comercio de Automotores", "employee_count":33},
        {"year": 2011,"gender": "Male", "cbo": "Comercio varejista", "employee_count":8},
        {"year": 2011,"gender": "Male", "cbo": "Comercio atacadista", "employee_count":21},
        {"year": 2011,"gender": "Male", "cbo": "Comercio de Automotores", "employee_count":30}
    ];